### ISSUE TITLE
Simple test case leaking ops

### ISSUE THREAD

**Issue by acrodrig** [eveningkid/denodb#328]
When I run the following simple test, I get leaked ops. Am I doing something wrong? Please advise and thanks much.

```typescript
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";
import { Database, DataTypes, Model, MySQLConnector } from 'https://deno.land/x/denodb/mod.ts';

class Account extends Model {
    static table = "Account";
    static fields = {
        id: { primaryKey: true, autoIncrement: true },
        name: DataTypes.STRING,
    };
}

// Connect and ping
const user = Deno.env.get("DB_USER") || "user";
const pass = Deno.env.get("DB_PASS") || "pass";
const connector = new MySQLConnector({ database: "db", host: "localhost", username: user, password: pass });
const db = new Database({ connector });

// Ping
await db.ping();

// Link
db.link([Account]);

Deno.test("DB should be empty", async function () {
    const accounts = await Account.all();
    assertEquals(accounts.length, 0);
});

await db.close();
```

Output:

```
DB should be empty
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 27
  - completed: 24
After:
  - dispatched: 84
  - completed: 82
Ops:
  op_sleep:
    Before:
      - dispatched: 8
      - completed: 6
    After:
      - dispatched: 27
      - completed: 26
```
